spring:
  datasource:
    url: jdbc:sqlserver://swatii.database.windows.net:1433;database=mydb;user=swatii@swatii;password=Shukla@212106;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.SQLServer2012Dialect
    
server:
  port: '8083'
